### ISSUE TITLE
getTodos nie pobiera aktualnych danch

### ISSUE THREAD

**Issue by aleksanderbastek** [aleksanderbastek/todo#10]
Jeżeli podpunkt listy zostanie usunięty, a użytkownik chce później wybrać opcje "wszystko" by wyświetlić wszystkie (zaznaczone i niezaznaczone) punkty listy wtedy getTodos pobiera wszystkie punkty razem z usuniętymi. Błąd nie występuje podczas ładowania strony, gdzie również pobierane są todos.

Na chwilę obecną po naciśnięciu opcji "wszystko" strona się odświeża i daje poprawną listę. Dałem tam location.reload() zamiast getTodos.

Dodaje zdjęcie z debuggera, gdzie pokazany jest powyższy problem.

![Przechwytywanie](https://user-images.githubusercontent.com/62114300/86781272-f7cb2a80-c05d-11ea-9d96-7733d4784c9d.PNG)

**Comment by thebartekbanach** [comment]
Cacheowanie apollo, zamykam. 😆
